import { Trash2, AlertCircle, Info } from 'lucide-react';

interface DeletePostModalProps {
  onConfirm: () => void;
  onCancel: () => void;
  isAutoGenerated?: boolean;
  postType?: string;
}

export default function DeletePostModal({ onConfirm, onCancel, isAutoGenerated = false, postType }: DeletePostModalProps) {
  const getMediaTypeText = () => {
    if (postType === 'profile_photo') return 'profile photo';
    if (postType === 'cover_photo') return 'cover photo';
    if (postType === 'album_media') return 'album photos and videos';
    return 'media';
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-lg max-w-md w-full shadow-xl">
        <div className="p-6">
          <div className="flex items-center justify-center w-12 h-12 rounded-full bg-red-100 mx-auto mb-4">
            <AlertCircle className="w-6 h-6 text-red-600" />
          </div>

          <h2 className="text-xl font-bold text-gray-900 text-center mb-2">
            Delete Post?
          </h2>

          <p className="text-gray-600 text-center mb-4">
            Are you sure you want to delete this post? This action cannot be undone.
          </p>

          {isAutoGenerated && (
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 mb-4">
              <div className="flex gap-2">
                <Info className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
                <p className="text-sm text-blue-900">
                  This will remove the post from your feed, but your {getMediaTypeText()} will remain in your profile and albums.
                </p>
              </div>
            </div>
          )}

          <div className="flex gap-3">
            <button
              onClick={onCancel}
              className="flex-1 px-4 py-2.5 bg-gray-200 text-gray-700 font-semibold rounded-lg hover:bg-gray-300 transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={onConfirm}
              className="flex-1 px-4 py-2.5 bg-red-600 text-white font-semibold rounded-lg hover:bg-red-700 transition-colors flex items-center justify-center gap-2"
            >
              <Trash2 className="w-4 h-4" />
              Delete
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
