import { Users, Camera, MessageCircle, Video, Mic, PenTool } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function SocialIconsSection() {
  const icons = [
    { Icon: Users, color: 'bg-orange-500', label: 'Heddit', link: '/heddit' },
    { Icon: Camera, color: 'bg-blue-500', label: 'Hinsta', link: '/hinsta' },
    { Icon: MessageCircle, color: 'bg-blue-600', label: 'HuBook', link: '/hubook' },
    { Icon: Video, color: 'bg-red-500', label: 'HuTube', link: '/hutube' },
    { Icon: Mic, color: 'bg-yellow-500', label: 'Switter', link: '/switter' },
    { Icon: PenTool, color: 'bg-slate-500', label: 'HuBlog', link: '/blog' },
  ];

  return (
    <section className="bg-white py-12 md:py-16">
      <div className="max-w-7xl mx-auto px-4">
        <h2 className="text-2xl md:text-4xl font-bold text-center mb-4">
          Now More Than Ever, It's Time to Connect and Reclaim Our Human Voice
        </h2>
        <p className="text-center text-gray-600 mb-10 md:mb-12 max-w-3xl mx-auto text-sm md:text-base">
          Recent studies indicate that upwards of 80% of global internet traffic is now generated by bots. That ends here at Sentient Portal. Join the movement! We're not just human-only: we're human-focused in everything that we offer.
        </p>

        <div className="grid grid-cols-3 sm:grid-cols-6 gap-6 md:gap-10 lg:gap-16 max-w-2xl sm:max-w-none mx-auto">
          {icons.map(({ Icon, color, label, link }, index) => (
            <Link key={index} to={link} className="flex flex-col items-center group">
              <div className={`${color} rounded-full p-4 md:p-6 shadow-lg hover:scale-110 transition-transform cursor-pointer`}>
                <Icon className="text-white" size={24} />
              </div>
              <span className="mt-2 md:mt-3 text-xs md:text-sm text-gray-700 text-center font-medium">{label}</span>
            </Link>
          ))}
        </div>
      </div>
    </section>
  );
}
